# This is a basic workflow to help you get started with Actions

name: Angular GKE

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev-deployment branch
  push:
    branches: [ angular-gke-deployment ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master # Set up ADC for credentials
        with:
          service_account_key: ${{ secrets.GET_GKE_CRED_SA_KEY_JSON }}
          export_default_credentials: true

      
      - id: get-kubeconfig
        uses: ./.github/get-gke-credentials
        with:
          project_id: ${{ secrets.GET_GKE_CRED_PROJECT }}
          cluster_name: ${{ secrets.GET_GKE_CRED_CLUSTER_NAME }}
          location: ${{ secrets.GET_GKE_CRED_CLUSTER_LOCATION }}
          use_auth_provider: true

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
          check-latest: true

      - id: install-npm
        name: install angular
        run: |-
          npm install -g @angular/cli
          npm install -g yarn 
          yarn
          
          
      - id: build
        working-directory: ./angular-gke
        name: Build angular   
        run: npm run publish

      - name: copy Dockerfile, nginx conf
        working-directory: ./angular-gke
        run: |-
          cp ./Dockerfile ./dist/Dockerfile
          cp ./nginx.conf ./dist/nginx.conf
          
      - name: Build image  
        working-directory: ./angular-gke/dist
        run: |-
          gcloud config set project GET_GKE_CRED_PROJECT
          gcloud builds submit -t gcr.io/${{ secrets.GET_GKE_CRED_PROJECT }}/angular-gke-sample .
          kubectl rollout restart deployment/angular-gke-sample